version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ocr_fastapi
    command:
      [
        "poetry",
        "run",
        "uvicorn",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "ocr_app.main:app",
        "--reload",
      ]
    ports:
      - 8000:8000
    networks:
      - ocr_network
    depends_on:
      - cache

  cache:
    image: redis:latest
    container_name: ocr_redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server 
    networks:
      - ocr_network

networks:
  ocr_network:
    driver: bridge
